# This file was generated by GoReleaser. DO NOT EDIT.
cask "pkgtui" do
  version "1.8.0"

  on_macos do
    on_arm do
      sha256 "564457dd1b8c137ef2590975ef8e055eab0a710cc4bda75239e5c856ab580148"
      url "https://github.com/padovanl/pkgtui/releases/download/v#{version}/pkgtui_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "77eab9bec73c2015e013c203a111ee0d7abbc16f6a4988f4f0b8a8f80b40858f"
      url "https://github.com/padovanl/pkgtui/releases/download/v#{version}/pkgtui_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a74f619c728a93f8384d994e4e141aa2fa4fd73f5edb8d8a0af7639793cbc870"
      url "https://github.com/padovanl/pkgtui/releases/download/v#{version}/pkgtui_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "705e4e1bf994d74b3fb2f61727ae8e8825d2399a99f133f974aa64a08c1d3fdc"
      url "https://github.com/padovanl/pkgtui/releases/download/v#{version}/pkgtui_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pkgtui"
  desc "htop-style terminal UI for apt, snap, flatpak, Homebrew and MacPorts packages"
  homepage "https://github.com/padovanl/pkgtui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pkgtui"

  # No zap stanza required
end
