# This file was generated by GoReleaser. DO NOT EDIT.
cask "pkgtui" do
  version "1.8.1"

  on_macos do
    on_arm do
      sha256 "37ca69e0b628d1137eb88d55c3c4b82d165c3666048ff809bafe09b772d68fcf"
      url "https://github.com/padovanl/pkgtui/releases/download/v#{version}/pkgtui_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5db702ba6e839dd646defb44b4b2c3aad7ce8d0f5401f9d402dedfb59b73ad25"
      url "https://github.com/padovanl/pkgtui/releases/download/v#{version}/pkgtui_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ece5be66bc35174420c7f211ca8e3cf922296bb7b34a6d331781f1a16c424a78"
      url "https://github.com/padovanl/pkgtui/releases/download/v#{version}/pkgtui_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b7d0242129246148e7ff5e24603c144e2f7516e60958eaee63d3c587da1d5827"
      url "https://github.com/padovanl/pkgtui/releases/download/v#{version}/pkgtui_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pkgtui"
  desc "htop-style terminal UI for apt, snap, flatpak, Homebrew and MacPorts packages"
  homepage "https://github.com/padovanl/pkgtui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pkgtui"

  # No zap stanza required
end
